server {
    listen 0.0.0.0:8080;
    client_max_body_size 1000000;
    error_page 404 web/error/404.html;
    error_page 500 web/error/500.html;

    location / {
        root web;
        methods GET POST DELETE;
        index index.html;
        autoindex off;
    }

    location /upload {
        root web;
        methods GET POST;
        upload on;
        upload_store web/uploads;
    }

    location /cgi-bin {
        root web/cgi-bin;
        methods GET POST;
        cgi .py /usr/bin/python3;
    }
}
