server {
    listen 127.0.0.1:18096;
    client_max_body_size 10;
    location / {
        root /tmp/webserv-limits-root;
        methods GET POST;
        index index.html;
        autoindex off;
        upload off;
    }
}
